# Generated by Django 5.1.7 on 2025-05-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='NumberQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number.number')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_quantities', to='stocks.stock')),
            ],
            options={
                'unique_together': {('stock', 'number')},
            },
        ),
    ]
