# Generated by Django 5.1.7 on 2025-05-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('collection', '0001_initial'),
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images_0', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('images_1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('images_2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('images_3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=13, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('variations', models.CharField(blank=True, max_length=200, null=True)),
                ('number_active', models.BooleanField(default=True)),
                ('size_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('collections', models.ManyToManyField(related_name='collections', to='collection.collection')),
                ('color', models.ManyToManyField(related_name='stocks', to='color.color')),
            ],
        ),
    ]
